import typing
from cryptography import utils as utils
from cryptography.exceptions import AlreadyFinalized as AlreadyFinalized, InvalidKey as InvalidKey, UnsupportedAlgorithm as UnsupportedAlgorithm, _Reasons as _Reasons
from cryptography.hazmat.backends import _get_backend as _get_backend
from cryptography.hazmat.backends.interfaces import HMACBackend as HMACBackend
from cryptography.hazmat.primitives import constant_time as constant_time, hashes as hashes, hmac as hmac
from cryptography.hazmat.primitives.kdf import KeyDerivationFunction as KeyDerivationFunction
from typing import Any

class HKDF(KeyDerivationFunction):
    _algorithm: Any = ...
    _salt: Any = ...
    _backend: Any = ...
    _hkdf_expand: Any = ...
    def __init__(self, algorithm: hashes.HashAlgorithm, length: int, salt: typing.Optional[bytes], info: typing.Optional[bytes], backend: Any=...) -> None: ...
    def _extract(self, key_material: bytes) -> bytes: ...
    def derive(self, key_material: bytes) -> bytes: ...
    def verify(self, key_material: bytes, expected_key: bytes) -> None: ...

class HKDFExpand(KeyDerivationFunction):
    _algorithm: Any = ...
    _backend: Any = ...
    _length: Any = ...
    _info: Any = ...
    _used: bool = ...
    def __init__(self, algorithm: hashes.HashAlgorithm, length: int, info: typing.Optional[bytes], backend: Any=...) -> None: ...
    def _expand(self, key_material: bytes) -> bytes: ...
    def derive(self, key_material: bytes) -> bytes: ...
    def verify(self, key_material: bytes, expected_key: bytes) -> None: ...
