import abc
from enum import Enum
from typing import Any

class Encoding(Enum):
    PEM: str = ...
    DER: str = ...
    OpenSSH: str = ...
    Raw: str = ...
    X962: str = ...
    SMIME: str = ...

class PrivateFormat(Enum):
    PKCS8: str = ...
    TraditionalOpenSSL: str = ...
    Raw: str = ...
    OpenSSH: str = ...

class PublicFormat(Enum):
    SubjectPublicKeyInfo: str = ...
    PKCS1: str = ...
    OpenSSH: str = ...
    Raw: str = ...
    CompressedPoint: str = ...
    UncompressedPoint: str = ...

class ParameterFormat(Enum):
    PKCS3: str = ...

class KeySerializationEncryption(metaclass=abc.ABCMeta): ...

class BestAvailableEncryption(KeySerializationEncryption):
    password: Any = ...
    def __init__(self, password: bytes) -> None: ...

class NoEncryption(KeySerializationEncryption): ...
