from cryptography import utils as utils
from cryptography.exceptions import AlreadyFinalized as AlreadyFinalized, UnsupportedAlgorithm as UnsupportedAlgorithm, _Reasons as _Reasons
from cryptography.hazmat.backends import _get_backend as _get_backend
from cryptography.hazmat.backends.interfaces import HMACBackend as HMACBackend
from cryptography.hazmat.primitives import hashes as hashes
from typing import Any

class HMAC(hashes.HashContext):
    _algorithm: Any = ...
    _backend: Any = ...
    _key: Any = ...
    _ctx: Any = ...
    def __init__(self, key: bytes, algorithm: hashes.HashAlgorithm, backend: Any=..., ctx: Any=...) -> None: ...
    algorithm: Any = ...
    def update(self, data: bytes) -> None: ...
    def copy(self) -> HMAC: ...
    def finalize(self) -> bytes: ...
    def verify(self, signature: bytes) -> None: ...
