from cryptography import utils as utils
from cryptography.exceptions import AlreadyFinalized as AlreadyFinalized, UnsupportedAlgorithm as UnsupportedAlgorithm, _Reasons as _Reasons
from typing import Any

class Poly1305:
    _ctx: Any = ...
    def __init__(self, key: bytes) -> None: ...
    def update(self, data: bytes) -> None: ...
    def finalize(self) -> bytes: ...
    def verify(self, tag: bytes) -> None: ...
    @classmethod
    def generate_tag(cls: Any, key: bytes, data: bytes) -> bytes: ...
    @classmethod
    def verify_tag(cls: Any, key: bytes, data: bytes, tag: bytes) -> None: ...
