import abc
from cryptography.exceptions import UnsupportedAlgorithm as UnsupportedAlgorithm, _Reasons as _Reasons
from cryptography.hazmat.primitives import _serialization as _serialization
from typing import Any

class Ed448PublicKey(metaclass=abc.ABCMeta):
    @classmethod
    def from_public_bytes(cls: Any, data: bytes) -> Ed448PublicKey: ...
    @abc.abstractmethod
    def public_bytes(self, encoding: _serialization.Encoding, format: _serialization.PublicFormat) -> bytes: ...
    @abc.abstractmethod
    def verify(self, signature: bytes, data: bytes) -> Any: ...

class Ed448PrivateKey(metaclass=abc.ABCMeta):
    @classmethod
    def generate(cls: Any) -> Ed448PrivateKey: ...
    @classmethod
    def from_private_bytes(cls: Any, data: bytes) -> Ed448PrivateKey: ...
    @abc.abstractmethod
    def public_key(self) -> Ed448PublicKey: ...
    @abc.abstractmethod
    def sign(self, data: bytes) -> bytes: ...
    @abc.abstractmethod
    def private_bytes(self, encoding: _serialization.Encoding, format: _serialization.PrivateFormat, encryption_algorithm: _serialization.KeySerializationEncryption) -> Any: ...
