from typing import Any, TypeVar, Union

T = TypeVar('T')
D = TypeVar('D')

class StoreKey:
    __slots__: Any = ...

class Store:
    __slots__: Any = ...
    _store: Any = ...
    def __init__(self) -> None: ...
    def __setitem__(self, key: StoreKey[T], value: T) -> None: ...
    def __getitem__(self, key: StoreKey[T]) -> T: ...
    def get(self, key: StoreKey[T], default: D) -> Union[T, D]: ...
    def setdefault(self, key: StoreKey[T], default: T) -> T: ...
    def __delitem__(self, key: StoreKey[T]) -> None: ...
    def __contains__(self, key: StoreKey[T]) -> bool: ...
