from _pytest.nodes import Item as Item
from typing import Any, List, Optional

DEFAULT_MAX_LINES: int
DEFAULT_MAX_CHARS: Any
USAGE_MSG: str

def truncate_if_required(explanation: List[str], item: Item, max_length: Optional[int]=...) -> List[str]: ...
def _should_truncate_item(item: Item) -> bool: ...
def _running_on_ci() -> bool: ...
def _truncate_explanation(input_lines: List[str], max_lines: Optional[int]=..., max_chars: Optional[int]=...) -> List[str]: ...
def _truncate_by_char_count(input_lines: List[str], max_chars: int) -> List[str]: ...
