from typing import Any

def cryptography_has_ec2m(): ...
def cryptography_has_rsa_oaep_md(): ...
def cryptography_has_rsa_oaep_label(): ...
def cryptography_has_ssl3_method(): ...
def cryptography_has_102_verification(): ...
def cryptography_has_110_verification_params(): ...
def cryptography_has_set_cert_cb(): ...
def cryptography_has_ssl_st(): ...
def cryptography_has_tls_st(): ...
def cryptography_has_scrypt(): ...
def cryptography_has_evp_pkey_dhx(): ...
def cryptography_has_mem_functions(): ...
def cryptography_has_sct(): ...
def cryptography_has_x509_store_ctx_get_issuer(): ...
def cryptography_has_ed448(): ...
def cryptography_has_ed25519(): ...
def cryptography_has_poly1305(): ...
def cryptography_has_oneshot_evp_digest_sign_verify(): ...
def cryptography_has_evp_digestfinal_xof(): ...
def cryptography_has_evp_pkey_get_set_tls_encodedpoint(): ...
def cryptography_has_fips(): ...
def cryptography_has_ssl_sigalgs(): ...
def cryptography_has_psk(): ...
def cryptography_has_custom_ext(): ...
def cryptography_has_openssl_cleanup(): ...
def cryptography_has_tlsv13(): ...
def cryptography_has_keylog(): ...
def cryptography_has_raw_key(): ...
def cryptography_has_engine(): ...
def cryptography_has_verified_chain(): ...
def cryptography_has_srtp(): ...
def cryptography_has_get_proto_version(): ...

CONDITIONAL_NAMES: Any
