FROM stanislavlevin/freeipa-tests-altlinux:sisyphus
ENV container=docker LANG=en_US.utf8 LANGUAGE=en_US.utf8 LC_ALL=en_US.utf8

COPY dist /root
RUN \
    apt-get update \
    && apt-get install -y /root/rpms/*.rpm \
    && apt-get clean \
    && find /var/lib/apt/lists/ -type f -exec rm "{}" \; \
    && rm -rf /var/cache/apt/*.bin \
    && rm -rf /root/rpms /root/srpms
VOLUME ["/freeipa"]
ENTRYPOINT [ "/sbin/init" ]
