import typing
from cryptography.hazmat._types import _PRIVATE_KEY_TYPES as _PRIVATE_KEY_TYPES, _PUBLIC_KEY_TYPES as _PUBLIC_KEY_TYPES
from cryptography.hazmat.backends import _get_backend as _get_backend
from cryptography.hazmat.primitives.asymmetric import dh as dh
from typing import Any

def load_pem_private_key(data: bytes, password: typing.Optional[bytes], backend: Any=...) -> _PRIVATE_KEY_TYPES: ...
def load_pem_public_key(data: bytes, backend: Any=...) -> _PUBLIC_KEY_TYPES: ...
def load_pem_parameters(data: bytes, backend: Any=...) -> dh.DHParameters: ...
def load_der_private_key(data: bytes, password: typing.Optional[bytes], backend: Any=...) -> _PRIVATE_KEY_TYPES: ...
def load_der_public_key(data: bytes, backend: Any=...) -> _PUBLIC_KEY_TYPES: ...
def load_der_parameters(data: bytes, backend: Any=...) -> dh.DHParameters: ...
