from cryptography.exceptions import InvalidTag as InvalidTag
from typing import Any

_ENCRYPT: int
_DECRYPT: int

def _aead_cipher_name(cipher: Any): ...
def _aead_setup(backend: Any, cipher_name: Any, key: Any, nonce: Any, tag: Any, tag_len: Any, operation: Any): ...
def _set_length(backend: Any, ctx: Any, data_len: Any) -> None: ...
def _process_aad(backend: Any, ctx: Any, associated_data: Any) -> None: ...
def _process_data(backend: Any, ctx: Any, data: Any): ...
def _encrypt(backend: Any, cipher: Any, nonce: Any, data: Any, associated_data: Any, tag_length: Any): ...
def _decrypt(backend: Any, cipher: Any, nonce: Any, data: Any, associated_data: Any, tag_length: Any): ...
