from cryptography import utils as utils
from cryptography.exceptions import UnsupportedAlgorithm as UnsupportedAlgorithm, _Reasons as _Reasons
from cryptography.hazmat.primitives import hashes as hashes
from typing import Any

class _HashContext(hashes.HashContext):
    _algorithm: Any = ...
    _backend: Any = ...
    _ctx: Any = ...
    def __init__(self, backend: Any, algorithm: hashes.HashAlgorithm, ctx: Any=...) -> None: ...
    algorithm: Any = ...
    def copy(self) -> _HashContext: ...
    def update(self, data: bytes) -> None: ...
    def finalize(self) -> bytes: ...
    def _finalize_xof(self) -> bytes: ...
