from cryptography import utils as utils
from cryptography.exceptions import InvalidSignature as InvalidSignature, UnsupportedAlgorithm as UnsupportedAlgorithm, _Reasons as _Reasons
from cryptography.hazmat.primitives import constant_time as constant_time, hashes as hashes
from typing import Any

class _HMACContext(hashes.HashContext):
    _algorithm: Any = ...
    _backend: Any = ...
    _ctx: Any = ...
    _key: Any = ...
    def __init__(self, backend: Any, key: bytes, algorithm: hashes.HashAlgorithm, ctx: Any=...) -> None: ...
    algorithm: Any = ...
    def copy(self) -> _HMACContext: ...
    def update(self, data: bytes) -> None: ...
    def finalize(self) -> bytes: ...
    def verify(self, signature: bytes) -> None: ...
