from cryptography import utils as utils
from cryptography.hazmat.primitives import hashes as hashes
from cryptography.hazmat.primitives.asymmetric.utils import Prehashed as Prehashed
from typing import Any

def _evp_pkey_derive(backend: Any, evp_pkey: Any, peer_public_key: Any): ...
def _calculate_digest_and_algorithm(backend: Any, data: Any, algorithm: Any): ...
def _check_not_prehashed(signature_algorithm: Any) -> None: ...
def _warn_sign_verify_deprecated() -> None: ...
