from cryptography.hazmat.backends.openssl.utils import _evp_pkey_derive as _evp_pkey_derive
from cryptography.hazmat.primitives import serialization as serialization
from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey as X25519PrivateKey, X25519PublicKey as X25519PublicKey
from typing import Any

_X25519_KEY_SIZE: int

class _X25519PublicKey(X25519PublicKey):
    _backend: Any = ...
    _evp_pkey: Any = ...
    def __init__(self, backend: Any, evp_pkey: Any) -> None: ...
    def public_bytes(self, encoding: serialization.Encoding, format: serialization.PublicFormat) -> bytes: ...
    def _raw_public_bytes(self) -> bytes: ...

class _X25519PrivateKey(X25519PrivateKey):
    _backend: Any = ...
    _evp_pkey: Any = ...
    def __init__(self, backend: Any, evp_pkey: Any) -> None: ...
    def public_key(self) -> X25519PublicKey: ...
    def exchange(self, peer_public_key: X25519PublicKey) -> bytes: ...
    def private_bytes(self, encoding: serialization.Encoding, format: serialization.PrivateFormat, encryption_algorithm: serialization.KeySerializationEncryption) -> bytes: ...
    def _raw_private_bytes(self) -> bytes: ...
